// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN0IC7Zww2bmBNDdx8Iuapgjb0gPvBf3Y',
    appId: '1:1023264748938:android:d6fba474bb8f47645e4473',
    messagingSenderId: '1023264748938',
    projectId: 'dhabiha-eaecf',
    storageBucket: 'dhabiha-eaecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQGFowp4PsY2hqEmOeIT-xmMVXPBdY89U',
    appId: '1:1023264748938:ios:8df0671640d4d3925e4473',
    messagingSenderId: '1023264748938',
    projectId: 'dhabiha-eaecf',
    storageBucket: 'dhabiha-eaecf.appspot.com',
    androidClientId: '1023264748938-3gdu3pc00fvg5ieqvtbeup5vk2df1rqj.apps.googleusercontent.com',
    iosClientId: '1023264748938-9vcfh6hjcm65gm3fe1b4vhi4lu5krov9.apps.googleusercontent.com',
    iosBundleId: 'com.skylight.dhabihaapp',
  );
}
